### ISSUE TITLE
Making the demo work

### ISSUE THREAD

**Issue by jamesaoverton** [INCATools/semantic-sql#4]
I made this work, but it took a lot of doing. Sorry to dump problems instead of fixes but I'm out of time today:

- the `Makefile` requires `reports/obo.tsv` on the first line, but it isn't built until later
- the Makefile doesn't create all the directories it needs, so lots of tasks fail
- you can download a rdftab binary from the repo, you don't need to build it
- you can add this to your makefile to fetch the rdftab binary: <https://github.com/obi-ontology/obi/blob/master/Makefile#L49>
- ROBOT needs to be on your PATH
- [relation-graph](https://github.com/balhoff/relation-graph) needs to be on your PATH
- I thought I needed to set up Python (venv and pip install requirements) but I guess I didn't
- line 75 should be `robot merge -i $< -i inferences/$*-nr.ttl -o $@` with `$*` instead of `%`

Then I got `make db/pato.db` to work.

**Comment by cmungall** [comment]
thanks, and sorry for the lack of warnings re things changing under feet and flaky instructions. I'd like to do a Dockerfile but for now I will fix the instructions as I need to tweak the README anyway

**Comment by cmungall** [comment]
@hrshdgd will take a look at this and #5

**Comment by cmungall** [comment]
yes the python is totally optional for building a db and adding the views (though required for a `make test`)

**Comment by cmungall** [comment]
Everything has been considerably refactored and can all be done with docker next odk release
