### ISSUE TITLE
Make a Dockerfile

### ISSUE THREAD

**Issue by cmungall** [INCATools/semantic-sql#6]
Instructions are getting harder to run (maybe time to split into different repos?) see #4

**Comment by cmungall** [comment]
First pass: 9a7f39e5098abbc3780a906c12f0fb6340ae95da

as a first pass, just get in sufficient stuff to be able to build the sqlite dbs

then we can include the python, but this may eventually move to a separate repo

**Comment by hrshdhgd** [comment]
@cmungall sqlite db can be queried.

**Comment by cmungall** [comment]
This is now in the latest ODK
