### ISSUE TITLE
Weird offset in picking prefixes

### ISSUE THREAD

**Issue by matentzn** [INCATools/semantic-sql#71]
Given http://purl.obolibrary.org/obo/xao.owl

turned into sql like:

```
xao.db: xao.owl
	@rm -f .template.db
	@rm -f .template.db.tmp
	RUST_BACKTRACE=full semsql make $@
	@rm -f .template.db
	@rm -f .template.db.tmp
```

The wrong prefixes are assigned.

For example:

```
runoak -i sqlite:ontologies/xao.db terms 
ZFA:0005234 ! small secretory cell
ZFA:0005235 ! dorsal telencephalon
...
```

It should be:

```
XAO:0005234 ! small secretory cell
XAO:0005235 ! dorsal telencephalon
```

This is a pretty dangerous error and should be prioritised above everything else.

cc @hrshdhgd

**Comment by matentzn** [comment]
I noticed that given a prefix map, the _next prefix in line_ is picked. I am assuming this is an issue with an index access on the prefix map.

semsql should be using the `curies` module for this!

**Comment by hrshdhgd** [comment]
Solved by https://github.com/INCATools/ontology-development-kit/pull/833
