### ISSUE TITLE
Update ontology builds in S3 bucket

### ISSUE THREAD

**Issue by rsgoncalves** [INCATools/semantic-sql#76]
> Pre-generated SQLite database are created weekly for all OBO ontologies and a selection of others (see [ontologies.yaml](https://github.com/INCATools/semantic-sql/blob/main/src/semsql/builder/registry/ontologies.yaml))

It doesn't look like up-to-date builds are accessible from the S3 bucket URLs— at least not for EFO. Am I missing something or are the SQL builds not updated so regularly?

**Comment by turbomam** [comment]
I would like to have a semantic sql representation of the current EnvO release in S3

**Comment by caufieldjh** [comment]
For most ontologies on that bucket, the most recent version will be the `db.gz`.
Looks like `envo.db.gz` last got updated on Feb 12 2024 - so if that's not in alignment with the most recent release then there's a bigger issue here.
Same for `efo.db.gz` - last updated Feb 12.

**Comment by cmungall** [comment]
That's right. Note the filestamp tells you the time of build. To get the actual versionIRI you can query it:

```bash
✗ sqlite3 ~/.data/oaklib/envo.db
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> select * from statements where predicate='owl:versionIRI';
obo:envo.owl|obo:envo.owl|owl:versionIRI|obo:envo/releases/2024-02-05/envo.owl||||
```

__NOTE__ if you are accessing ENVO via OAK be aware that pystow does not have any explicit cache management, you need to remove `~/.data/oaklib/envo.db` and `~/.data/oaklib/envo.db.gz` to trigger a re-download
